### ISSUE TITLE
SDK MANUAL - Master Slave jargon is present in manuals attached to wikis

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_sdk#216]
I guess this is the right repo for this issue. 

The title is self-explanatory. We should ban this jargon from our materials for reasons I hope will speak to all of us.

Let's replace with ex: leader, follower (not good one but just wanted to start and idea) has to be something smooth and that falls out of debates

**Comment by Sacha96** [comment]
@sasha-astiadi does this relate to your current story? https://circles.threefold.me/project/despiegk-tf_team_grid/us/689?milestone=28

**Comment by Vilnite** [comment]
Issue should point to an action that needs to be taken. @Sacha96 can you clarify a step/-s to be taken here?
Can we link this with dictionary aka TF term definitions solution @despiegk is working on?

**Comment by Sacha96** [comment]
To me yes, but it would require extra work, and right now there are other prios so lets keep in backlog for now

**Comment by weynandkuijpers** [comment]
Even though the industry uses "master" and "slave" and slave terminology a lot I agree with @Sacha96 that this is no longer appropriate.  There are alternatives (many for it that are also understood.  Best one according to my book is:
- master -> primary (server)
- slave -> secondary of failover (server).

**Comment by xmonader** [comment]
I fully agree such terms need to be out of this organization manuals, code, ... everywhere

**Comment by weynandkuijpers** [comment]
Will do a search and rewrite the sections (minor) where the words master/slacve are used.  I understand that this jargon is used in the world of IT but we have far better ways to describe this. today.

**Comment by weynandkuijpers** [comment]
File found in the info_threefold report that had the word master in it:
```
~/codewww/github/threefoldfoundation/info_threefold$ grep -r -l -i master           
```
- [ ] src/tf_history/genesis_block_pool_details.md
- [ ] src/communication/launch_announcements/ttzero0s.md
- [ ] src/communication/launch_announcements/tomochainintro.md
- [ ] src/communication/launch_announcements/recap1.md
- [ ] src/grants/vrmuseum/vrmuseum.md
- [ ] src/hiring/hiring_overview.md
- [ ] src/hiring/tech_protocolme_architect.md
- [ ] src/farming/farming_manual/delete_zero_boot_hardware.md
- [ ] src/farming/farming_manual/zero_boot_hardware.md
- [ ] src/token/stellar_migration/tft_tfta_migration_process_technical.md
- [ ] src/token/_beta/technology/proof_of_blockstake.md
- [ ] src/token/_beta/technology/beta_atomic_swaps.md
- [ ] src/token/how_to_buy/tft_mazraa.md
- [ ] src/token/how_to_buy/tft_liquid.md
- [ ] src/token/how_to_buy/tft_btc_alpha_later.md
- [ ] src/token/apps_wallets/threefold_app.md
- [ ] src/sidebar.md
- [ ] src/release_mgmt/release_notes_2_8_0.md
- [ ] src/collaboration/freeflow_tools/_archive/archive_links.md
- [ ] src/collaboration/freeflow_tools/circles_tools.md
- [ ] src/collaboration/freeflow_tools/github_content_rules.md
- [ ] src/collaboration/freeflow_tools/markdown.md
- [ ] src/collaboration/tftools.md
- [ ] src/collaboration/values/veda_values.md
- [ ] src/collaboration/tips_tricks/slides_master_template_tips.md
- [ ] src/collaboration/org40/on_leadership.md
- [ ] src/sustainability/energy_savings_storage.md
- [ ] README.md
- [ ] src_archive/technology/technology_components_hercules/hercules_storage.md
- [ ] src_archive/technology/technology_components_hercules/hercules_compute.md
- [ ] src_archive/technology/technology_overview/technology_overview_parts/technical_components_overview.md

**Comment by weynandkuijpers** [comment]
Other `codewww` repositories:
```
~/codewww/github$ grep -r -l -i slave  
```
- [ ] threefoldtech/info_tftech/src/technology/threefold_cloud/vdc_storage.md
- [ ] veda-online/info_veda/src/trip/temples.md
- [ ] threefoldfoundation/info_sdk/src/architecture/archi_qscompute.md
- [ ] threefoldfoundation/info_sdk/src/develop/solutions/storage/code_hercule.md
- [ ] threefoldfoundation/info_sdk/.git/index
- [ ] threefoldfoundation/info_sdk/.git/objects/pack/pack-84754e26e4b7527a7ce19f6906386df9738d4121.pack
- [ ] threefoldfoundation/info_threefold/src/sustainability/energy_savings_storage.md
- [ ] threefoldfoundation/info_threefold/src_archive/technology/technology_components_hercules/hercules_storage.md
- [ ] threefoldfoundation/info_threefold/src_archive/technology/technology_overview/technology_overview_parts/technical_components_overview.md
- [ ]  threefoldfoundation/info_threefold/.git/logs/refs/heads/development_issue_216
- [ ] threefoldfoundation/info_threefold/.git/logs/HEAD
- [ ] threefoldfoundation/info_threefold/.git/COMMIT_EDITMSG
- [ ] threefoldfoundation/info_cloud/src/marketplace/minio.md
- [ ] threefoldfoundation/info_cloud/to_sort/threefold_now/minio.md
- [ ] threefoldfoundation/master.out

**Comment by weynandkuijpers** [comment]
All repos / wiki check and rewriten.  Not always opened a new branch as somethimes it was only one edit per branch / repo.
