### ISSUE TITLE
documentation how to setup a gateway

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_sdk#317]
- also example in the client side of it, that we cannot guarantee not measure if web gw are working
- we document a few which are working so can be used

**Comment by xmonader** [comment]
> LEt me know if I can help to create a document from raw engineering material - just point me to the right place @xmonader

@weynandkuijpers  Would be amazing, the documentation exists already here https://github.com/threefoldtech/tfgateway/blob/master/README.md

**Comment by xmonader** [comment]
docs added here https://github.com/threefoldfoundation/info_cloud/commit/f6d14ba6f05f0c295f1629948c80712f8211e3d0 

@weynandkuijpers please feel free add any updates you need
