### ISSUE TITLE
SDK Manual – Fix Issue with 3Bot Definition

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_sdk#324]
When I click on 3Bot on the Sidebar, I am brought to this page:

https://new.threefold.io/info/sdk#/sdk__3bot

There is a linking issue here because it is pulling the 3Bot definition instead of the 3Bot Deployer.

Markdown looks correct:

Follow the instructions on [3Bot Deployer](3bot_deployer) to install your 3Bot - your virtual system administrator.

Waiting on instructions on how to override definitions.

**Comment by samtaggart** [comment]
@despiegk Please look into this, it's related to #386

**Comment by Vilnite** [comment]
@samtaggart please check if this is still an issue

**Comment by samtaggart** [comment]
Looks fine now.
