### ISSUE TITLE
Push sdk wiki on production

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_sdk#332]

**Comment by sasha-astiadi** [comment]
same as https://github.com/threefoldfoundation/info_sdk/issues/332

**Comment by hossnys** [comment]
updated staging and production

**Comment by Vilnite** [comment]
Changes are not being pulled in. See last commit on development.

**Comment by sasha-astiadi** [comment]
@hossnys could you please pull one more time, had new changes on development

**Comment by hossnys** [comment]
fixed and all changes are live now 

![Screenshot from 2021-08-08 13-21-25](https://user-images.githubusercontent.com/26298009/128630341-ef0dbacb-da5e-467d-ad03-fb56f5f11af5.png)
