### ISSUE TITLE
MANUAL 3.0 - Link in manual not working 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_sdk#335]
Getting 404 error 

https://library.threefold.me/info/manual/#/manual__tfgrid3_getstarted.dev.bootstrap.grid.tf

**Comment by Vilnite** [comment]
@sabrinasadik can you please share where this link is located?

**Comment by sabrinasadik** [comment]
All I have is the following info from the user:
"There is a link just before the place to enter the farm ID labelled "You can find more information here". That link gives me a 404-Not found error."

**Comment by scottyeager** [comment]
The issue is actually that the link from the bootstrap site to the manual is broken. Should go here: https://library.threefold.me/info/manual/#/manual__farming

I'm not sure where the code for the bootstrap lives... will investigate.
